version: '3'
services:
  lliwio_nginx:
    image: nginx:alpine
    container_name: lliwio_nginx
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - lliwio_api
    ports: 
      - "80:80"
  
  lliwio_api:
    build: ./api
    container_name: lliwio_api

  # lliwio_frontend:
  #   build: ./ui/src
  #   volumes: ./ui/src:/app/src
  #   ports:
  #     - "5050:5050"