version: '3'
services:
  lliwio_nginx:
    container_name: lliwio_nginx
    image: nginx:alpine
    volumes:
      - ./nginx/conf.d/dev:/etc/nginx/conf.d
    depends_on:
      - lliwio_api
      - lliwio_web_vis
    ports: 
      - "80:80"
  
  lliwio_api:
    container_name: lliwio_api
    build: 
      context: ./api
      dockerfile: Dockerfile-dev
    volumes:
      - ./api:/usr/src/app
    ports:
      - "3000:3000"

  lliwio_web_vis:
    container_name: lliwio_web_vis
    build:
      context: ./ui
      dockerfile: Dockerfile-dev
    volumes:
      - ./ui/src:/usr/src/app/src
    depends_on:
      - lliwio_api
    ports:
      - "5050:5050"
      - "35729:35729"