FROM node:9.1.0-alpine
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY package.json /usr/src/app
COPY ./src/gulpfile.js /usr/src/app
RUN npm install
COPY ./src /usr/src/app/src
EXPOSE 5050 35729
CMD ["npm", "start"]